#pragma once

#define BLYNK_WIFI_SSID "TIMEOSPACE"
#define BLYNK_WIFI_PASS "1234Saja"

// #define BLYNK_WIFI_SSID "silenceAndSleep"
// #define BLYNK_WIFI_PASS "11111111"

#define BLYNK_PRINT Serial
#define BLYNK_DEVICE_ID 1
#define BLYNK_DEVICE_NAME "Device 1"

#define BLYNK_TEMPLATE_ID "TMPL67qeJa1OC"
#define BLYNK_TEMPLATE_NAME "025 015 Nur"
#define BLYNK_AUTH_TOKEN "DNq10U88EJTJTMUF0miWe79TswfaITUr"

// #define BLYNK_TEMPLATE_ID "TMPL6yaFzTX5c"
// #define BLYNK_TEMPLATE_NAME "025 015 Nur"
// #define BLYNK_AUTH_TOKEN "0a1Ux49XYbIxb3nuaMOStN_-9kdxPiW1"

#define VIRTUAL_PIN_TEMPERATURE V0
#define VIRTUAL_PIN_HUMIDITY V1
#define VIRTUAL_PIN_TEMPERATURE_SETPOINT V2
#define VIRTUAL_PIN_UP_BUTTON V3
#define VIRTUAL_PIN_DOWN_BUTTON V4
#define VIRTUAL_PIN_POWER_BUTTON V5
#define VIRTUAL_PIN_POWER_STATUS V6
#define VIRTUAL_PIN_MODE_BUTTON V7